# Prepare the Data for the Machine Learning Model:

In [16]:
X_train.describe()

,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,...,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,103904.000000,103904.000000,103904.000000,103904.00000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,...,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000
mean,0.492955,39.434228,0.817100,0.30916,0.593981,1193.102547,14.791394,15.127839,3.056504,2.755794,...,2.975872,3.381188,3.441879,3.349948,3.288641,3.206325,3.639350,2.725805,3.360005,3.630101
std,0.499953,15.114814,0.386586,0.46215,0.622107,998.912433,38.165024,38.551079,1.528328,1.403130,...,1.278276,1.289531,1.319345,1.316656,1.312856,1.329301,1.178743,1.331548,1.333828,1.181821
min,0.000000,7.000000,0.000000,0.00000,0.000000,31.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,27.000000,1.000000,0.00000,0.000000,414.000000,0.000000,0.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,0.000000,40.000000,1.000000,0.00000,1.000000,846.000000,0.000000,0.000000,3.000000,3.000000,...,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,1.000000,51.000000,1.000000,1.00000,1.000000,1744.000000,12.000000,13.000000,4.000000,4.000000,...,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000
max,1.000000,85.000000,1.000000,1.00000,2.000000,4983.000000,1305.000000,1280.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [17]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)